# Generated by Django 5.1.4 on 2025-01-31 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('original_title', models.CharField(max_length=512)),
                ('is_adult', models.BooleanField(default=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('runtime_minutes', models.IntegerField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='imdb.genre')),
                ('movie_type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='imdb.movietype')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField(blank=True, null=True)),
                ('episode_number', models.IntegerField(blank=True, null=True)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='imdb.movie')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='imdb.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Akas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('title', models.CharField(max_length=512)),
                ('region', models.CharField(blank=True, max_length=4)),
                ('language', models.CharField(blank=True, max_length=4)),
                ('types', models.CharField(blank=True, max_length=50)),
                ('attributes', models.CharField(blank=True, max_length=255)),
                ('is_original_title', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('movies', models.ManyToManyField(blank=True, related_name='persons', to='imdb.movie')),
                ('professions', models.ManyToManyField(blank=True, related_name='persons', to='imdb.profession')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imdb.movie')),
                ('directors', models.ManyToManyField(blank=True, related_name='crew_directors', to='imdb.person')),
                ('writers', models.ManyToManyField(blank=True, related_name='crew_writers', to='imdb.person')),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('job', models.CharField(blank=True, max_length=255)),
                ('characters', models.CharField(blank=True, max_length=255)),
                ('ordering', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.person')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.FloatField()),
                ('num_votes', models.IntegerField()),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='imdb.movie')),
            ],
        ),
    ]
